//! 写 `~/.config/aura/config.toml`（slice 3）。
//!
//! 与 `crate::config::Config`（只读 + Deserialize）分离：这里是 onboarding 向导
//! 专用的 **写** 路径。写的内容是 `endpoint` / `model` / `provider` 三个字段，
//! 不写 `api_key`（key 只进 keychain，不进配置文件 —— 设计文档 §4.3）。
//!
//! 原子性：先写临时文件再 rename（避免半写状态）。

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use crate::error::AgentError;

/// 计算配置文件路径（与 `Config::config_path` 相同逻辑，但这里是写场景）。
#[must_use]
pub fn config_path() -> PathBuf {
    if let Some(p) = std::env::var_os("AURA_CONFIG") {
        return PathBuf::from(p);
    }
    if let Some(xdg) = std::env::var_os("XDG_CONFIG_HOME") {
        return PathBuf::from(xdg).join("aura").join("config.toml");
    }
    let home = std::env::var_os("HOME")
        .or_else(|| std::env::var_os("USERPROFILE"))
        .map(PathBuf::from);
    match home {
        Some(h) => h.join(".config").join("aura").join("config.toml"),
        None => PathBuf::from("config.toml"),
    }
}

/// 把 onboarding 结果写成 toml。`endpoint` / `model` / `provider` 必填。
///
/// # Errors
///
/// - `AgentError::ToolFailed` — 目录创建 / 临时文件写 / rename 失败
pub fn write(endpoint: &str, model: &str, provider: &str) -> Result<PathBuf, AgentError> {
    let path = config_path();
    write_to(&path, endpoint, model, provider)?;
    Ok(path)
}

/// 指定路径写入（测试用）。
pub(crate) fn write_to(
    path: &Path,
    endpoint: &str,
    model: &str,
    provider: &str,
) -> Result<(), AgentError> {
    let parent = path.parent().ok_or_else(|| {
        AgentError::ToolFailed(format!("config path has no parent: {}", path.display()))
    })?;
    fs::create_dir_all(parent).map_err(|e| {
        AgentError::ToolFailed(format!(
            "create config dir {} failed: {e}",
            parent.display()
        ))
    })?;

    // 内容：只写这 3 个字段（api_key 不落盘 —— key 在 keychain）
    let content = format!(
        "# Generated by `aura setup` — do not edit by hand unless you know what you're doing.\n\
         endpoint = {endpoint:?}\n\
         model = {model:?}\n\
         provider = {provider:?}\n"
    );

    // 原子写：临时文件 + rename
    let tmp = parent.join(format!(".config.toml.tmp-{}", std::process::id()));
    let mut f = fs::File::create(&tmp)
        .map_err(|e| AgentError::ToolFailed(format!("create {} failed: {e}", tmp.display())))?;
    f.write_all(content.as_bytes())
        .map_err(|e| AgentError::ToolFailed(format!("write {} failed: {e}", tmp.display())))?;
    f.sync_all()
        .map_err(|e| AgentError::ToolFailed(format!("sync {} failed: {e}", tmp.display())))?;
    fs::rename(&tmp, path).map_err(|e| {
        AgentError::ToolFailed(format!(
            "rename {} -> {} failed: {e}",
            tmp.display(),
            path.display()
        ))
    })?;

    // 权限 0600（含 api_key 时更关键；即使没有 key 也收紧了）
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = fs::set_permissions(path, fs::Permissions::from_mode(0o600));
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_dir() -> PathBuf {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir = std::env::temp_dir().join(format!("aura-config-write-test-{nanos}"));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn write_creates_file_with_fields() {
        let dir = temp_dir();
        let path = dir.join("config.toml");
        write_to(
            &path,
            "https://api.deepseek.com",
            "deepseek-chat",
            "deepseek",
        )
        .expect("write");
        let content = std::fs::read_to_string(&path).expect("read");
        assert!(content.contains("endpoint = \"https://api.deepseek.com\""));
        assert!(content.contains("model = \"deepseek-chat\""));
        assert!(content.contains("provider = \"deepseek\""));
        assert!(!content.contains("api_key"), "api_key must not be written");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn write_creates_parent_dirs() {
        let dir = temp_dir();
        let path = dir.join("nested").join("deeper").join("config.toml");
        write_to(&path, "ep", "m", "p").expect("write nested");
        assert!(path.exists());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn write_overwrites_existing() {
        let dir = temp_dir();
        let path = dir.join("config.toml");
        write_to(&path, "old", "old", "old").expect("write 1");
        write_to(&path, "new", "new", "new").expect("write 2");
        let content = std::fs::read_to_string(&path).expect("read");
        assert!(content.contains("provider = \"new\""));
        assert!(!content.contains("old"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn unix_permissions_are_600() {
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let dir = temp_dir();
            let path = dir.join("config.toml");
            write_to(&path, "ep", "m", "p").expect("write");
            let mode = fs::metadata(&path).unwrap().permissions().mode();
            assert_eq!(mode & 0o777, 0o600);
            let _ = std::fs::remove_dir_all(&dir);
        }
    }

    #[test]
    fn no_leftover_temp_files() {
        let dir = temp_dir();
        let path = dir.join("config.toml");
        write_to(&path, "ep", "m", "p").expect("write");
        let entries: Vec<_> = fs::read_dir(&dir)
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().to_string())
            .collect();
        assert_eq!(entries, vec!["config.toml"]);
        let _ = std::fs::remove_dir_all(&dir);
    }
}
